AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  discord-webhook-node
Globals:
  Function:
    Timeout: 10

Parameters:
  DiscordWebhookUrl:
    Type: String
    Default: webhookUrl
  AuthorName:
    Type: String
    Default: authorName

Resources:
  DiscordBotNodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        DiscordWebhook:
          Type: Schedule
          Properties:
            Schedule: cron(0 23 * * ? *)
      Environment:
        Variables:
          DISCORD_WEBHOOK_URL: !Ref DiscordWebhookUrl
          AUTHOR_NAME: !Ref AuthorName
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2020'
        Sourcemap: true
        EntryPoints:
          - app.ts

  DiscordBotNodeFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${DiscordBotNodeFunction}
      RetentionInDays: 14
